#define Ctrl_A      0x01
#define Ctrl_C      0x03
#define Ctrl_D      0x04
#define Bel         0x07
#define BS          0x08
#define Tab         0x09
#define NL          0x0a
#define CR          0x0d
#define Ctrl_N      0x0e
#define Ctrl_O      0x0f
#define Ctrl_R      0x12
#define Ctrl_X      0x18
#define Esc         0x1b
#define SP          0x20
#define Del         0x7f
#define Up          'A'
#define Down        'B'
#define Right       'C'
#define Left        'D'
#define PgUp        'I'
#define PgDown      'G'

